# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.Author'),
        ),
        migrations.AddField(
            model_name='painting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.Category'),
        ),
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.ImageField(null=True, upload_to='paintings'),
        ),
        migrations.AddField(
            model_name='painting',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.Style'),
        ),
        migrations.AddField(
            model_name='painting',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
