# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='logo',
            field=models.ImageField(null=True, upload_to='authors', verbose_name='Логотип'),
        ),
    ]
