# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_auto_20170308_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='slug',
            field=models.SlugField(max_length=30, verbose_name='URL'),
        ),
    ]
