# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0008_style_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='molding',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='molding/thumbnail', verbose_name='Предпросмотр'),
        ),
    ]
