# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_molding_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='molding',
            name='widthImage',
            field=models.IntegerField(null=True, verbose_name='Ширина рамки в изображении'),
        ),
    ]
