# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import museum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_number'),
        ('museum', '0010_molding_widthimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('execution', models.CharField(max_length=16, validators=[museum.validators.validate_exec])),
                ('lacquer', models.BooleanField(default=False)),
                ('struc_gel', models.BooleanField(default=False)),
                ('molding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.Molding')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='painting',
            name='aspect_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Painting'),
        ),
    ]
