# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import museum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0013_auto_20170905_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='logo',
            field=models.ImageField(default=1, upload_to='authors', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='execution',
            field=models.CharField(default='canvas', max_length=16, validators=[museum.validators.validate_exec]),
        ),
        migrations.AlterField(
            model_name='item',
            name='molding',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.Molding'),
        ),
        migrations.AlterField(
            model_name='molding',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='molding/thumbnail', verbose_name='Предпросмотр'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='molding',
            name='widthImage',
            field=models.IntegerField(default=100, verbose_name='Ширина рамки в изображении'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='aspect_ratio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='full_image',
            field=models.ImageField(default=1, upload_to='paintings', verbose_name='Полное изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='painting',
            name='width',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='style',
            name='logo',
            field=models.ImageField(default=1, upload_to='styles', verbose_name='Логотип'),
            preserve_default=False,
        ),
    ]
