# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0016_item_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
