# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-28 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museum', '0017_auto_20180128_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64, null=True)),
                ('phone_num', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('county', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=96)),
                ('street', models.CharField(max_length=64)),
                ('house', models.CharField(max_length=64)),
                ('flat', models.CharField(max_length=64)),
                ('index', models.IntegerField()),
                ('order_status', models.CharField(default='processing', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.Order'),
        ),
    ]
