# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0018_auto_20180128_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='county',
            new_name='country',
        ),
    ]
