# Generated by Django 2.0.2 on 2018-02-15 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0020_auto_20180130_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='molding',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.Molding'),
        ),
        migrations.AlterField(
            model_name='item',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.Order'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.Style', verbose_name='Направление'),
        ),
    ]
